server:
  port: 8082

spring:
  application:
    name: swipe-service

  datasource:
    url: jdbc:postgresql://localhost:5432/swipe_service
    username: postgres
    password: password

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    config:
      uri: http://localhost:8888
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092

jwt:
  secret:
    access: LA4XZ8oPuhwbaGHpPZBA7j6AzdnaufJxcA3BqN8qu/c/1mKklF+60Ds0PH4W/+yDXtZ4Ptaij135LReqleMEwg==
    refresh: $40bibBIBBT9lhB4xcAq4PqxBBkpi0Gw5okd8GrlGaLzIYjSPfTG1Xc+WPT0UxqXfyDV4P5WuPMecRkwM+e8c5Q==
