server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}

minio:
  access:
    user: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
  bucket: ${MINIO_BUCKET}
  url: http://${MINIO_HOST}:${MINIO_PORT}

grpc:
  port: ${GRPC_PORT}
  enable-reflection: true